package com.codybot.app;

import com.codybot.prototype.ScreenCaptureService;
import android.accessibilityservice.AccessibilityService;
import android.accessibilityservice.GestureDescription;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.ColorSpace;
import android.graphics.Path;
import android.graphics.PixelFormat;
import android.hardware.HardwareBuffer;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.util.DisplayMetrics;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityEvent;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.Text;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class CodyAccessibilityService extends AccessibilityService {
 private WindowManager windowManager; private View overlayView; private TextView statusText; private View calibrationView; private final Handler handler=new Handler(Looper.getMainLooper());
 private final List<Runnable> pendingCompilation=new ArrayList<>(); private boolean compiling=false; private static volatile String lastTargetPackage=""; private volatile boolean calibrationInProgress=false; private final String calibrationLetters="ABCDEFGHIJKLMNOPQRSTUVWXYZ"; private int calibrationIndex=0; private float[] manualCalibrationCenters; private volatile float[] calibratedCenters; private TextRecognizer recognizer;
 private final Runnable overlayChecker=new Runnable(){public void run(){if(overlayView==null){if(Settings.canDrawOverlays(CodyAccessibilityService.this))showOverlay();else handler.postDelayed(this,1000);}}};
 private final BroadcastReceiver overlayReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(i==null)return;if(i.hasExtra("message")&&statusText!=null)statusText.setText(i.getStringExtra("message"));String a=i.getAction();if("com.codybot.FILL_ANSWER".equals(a)){String s=i.getStringExtra("answer");if(s!=null&&!s.trim().isEmpty()&&ScreenCaptureService.isServiceRunning())fillAnswer(s);}else if("com.codybot.STOP_COMPILATION".equals(a))stopCompilation();else if("com.codybot.TEST_KEYBOARD".equals(a)){if(ScreenCaptureService.isServiceRunning())runKeyboardTest();else updateOverlayText("⚠️ TEST: avvia prima START");}else if("com.codybot.CALIBRATE_KEYBOARD".equals(a))startManualKeyboardCalibration();else if("com.codybot.HIDE_OVERLAY".equals(a))hideOverlay();}};
 @Override public void onAccessibilityEvent(AccessibilityEvent e){if(e!=null&&e.getPackageName()!=null){String n=e.getPackageName().toString();if(!n.equals(getPackageName())&&!n.equals("android")&&!n.equals("com.android.systemui"))lastTargetPackage=n;}if(overlayView==null&&Settings.canDrawOverlays(this))handler.post(overlayChecker);}
 public static String getLastTargetPackage(){return lastTargetPackage;}
 @Override protected void onServiceConnected(){super.onServiceConnected();recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);loadManualCalibration();try{registerReceiver(overlayReceiver,new IntentFilter("com.codybot.UPDATE_OVERLAY"));registerReceiver(overlayReceiver,new IntentFilter("com.codybot.FILL_ANSWER"));registerReceiver(overlayReceiver,new IntentFilter("com.codybot.STOP_COMPILATION"));registerReceiver(overlayReceiver,new IntentFilter("com.codybot.TEST_KEYBOARD"));registerReceiver(overlayReceiver,new IntentFilter("com.codybot.CALIBRATE_KEYBOARD"));}catch(Exception ignored){}handler.post(overlayChecker);}
 private void showOverlay(){if(overlayView!=null||!Settings.canDrawOverlays(this))return;windowManager=(WindowManager)getSystemService(WINDOW_SERVICE);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER_HORIZONTAL);l.setBackgroundColor(Color.parseColor("#CC000000"));l.setPadding(18,8,18,8);statusText=new TextView(this);statusText.setText("CodyBot 3.1 PRONTO");statusText.setTextColor(Color.WHITE);statusText.setTextSize(14);statusText.setGravity(Gravity.CENTER);statusText.setMaxLines(6);l.addView(statusText,new LinearLayout.LayoutParams(-1,-2));LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER);Button start=new Button(this);start.setText("START");start.setOnClickListener(v->{Intent i=new Intent(this,ScreenCaptureService.class);i.setAction(ScreenCaptureService.ACTION_START_SCAN);try{startService(i);}catch(Exception e){updateOverlayText("Errore: "+e.getClass().getSimpleName());}});Button stop=new Button(this);stop.setText("STOP");stop.setOnClickListener(v->{stopCompilation();Intent i=new Intent(this,ScreenCaptureService.class);i.setAction(ScreenCaptureService.ACTION_PAUSE_CAPTURE);try{startService(i);}catch(Exception e){updateOverlayText("STOP: "+e.getClass().getSimpleName());}});b.addView(start);b.addView(stop);l.addView(b);overlayView=l;DisplayMetrics dm=getResources().getDisplayMetrics();WindowManager.LayoutParams p=new WindowManager.LayoutParams((int)(dm.widthPixels*.92f),-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;p.y=70;try{windowManager.addView(overlayView,p);}catch(Exception e){overlayView=null;handler.postDelayed(overlayChecker,1000);}}
 private void startManualKeyboardCalibration(){stopCompilation();if(!Settings.canDrawOverlays(this)){updateOverlayText("⚠️ Attiva prima la sovrapposizione");return;}if(calibrationView!=null)removeCalibrationOverlay();LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setGravity(Gravity.CENTER_HORIZONTAL);p.setPadding(28,24,28,24);p.setBackgroundColor(Color.parseColor("#EE111111"));TextView t=new TextView(this);t.setText("🔧 CALIBRAZIONE TASTIERA");t.setTextColor(Color.WHITE);t.setTextSize(20);t.setGravity(Gravity.CENTER);p.addView(t,new LinearLayout.LayoutParams(-1,-2));TextView m=new TextView(this);m.setText("1. Apri CodyCross.\n\n2. Entra in una domanda e lascia visibile tutta la tastiera.\n\n3. Premi AVVIA ACQUISIZIONE.\n\nCodyBot chiederà A, B, C... fino a Z.");m.setTextColor(Color.WHITE);m.setTextSize(16);m.setPadding(0,20,0,20);p.addView(m,new LinearLayout.LayoutParams(-1,-2));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER);Button c=new Button(this);c.setText("ANNULLA");c.setOnClickListener(v->removeCalibrationOverlay());Button s=new Button(this);s.setText("AVVIA ACQUISIZIONE");s.setOnClickListener(v->{removeCalibrationOverlay();updateOverlayText("🔧 Preparazione calibrazione...");handler.postDelayed(this::showManualCalibrationOverlay,500);});r.addView(c);r.addView(s);p.addView(r);calibrationView=p;DisplayMetrics dm=getResources().getDisplayMetrics();WindowManager.LayoutParams q=new WindowManager.LayoutParams((int)(dm.widthPixels*.90f),-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);q.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;q.y=120;try{windowManager.addView(calibrationView,q);}catch(Exception e){calibrationView=null;updateOverlayText("❌ Errore calibrazione: "+e.getClass().getSimpleName());}}
 private void showManualCalibrationOverlay(){if(!Settings.canDrawOverlays(this)){updateOverlayText("⚠️ Attiva prima la sovrapposizione");return;}DisplayMetrics dm=getResources().getDisplayMetrics();final int sw=dm.widthPixels,sh=dm.heightPixels;final float[] c=new float[52];calibrationIndex=0;calibrationInProgress=true;FrameLayout f=new FrameLayout(this);f.setBackgroundColor(Color.TRANSPARENT);f.setClickable(true);TextView p=new TextView(this);p.setTextColor(Color.WHITE);p.setTextSize(18);p.setGravity(Gravity.CENTER);p.setBackgroundColor(Color.parseColor("#DD000000"));p.setText("🔧 CALIBRAZIONE TASTIERA\n\nTocca la lettera A\n0/26");FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(-1,-2,Gravity.TOP);pp.topMargin=55;f.addView(p,pp);f.setOnTouchListener((v,e)->{if(!calibrationInProgress||e==null||e.getAction()!=android.view.MotionEvent.ACTION_UP)return true;if(e.getY()<220)return true;int i=calibrationIndex;if(i>=26)return true;c[i*2]=e.getX();c[i*2+1]=e.getY();calibrationIndex++;if(calibrationIndex<26){char n=calibrationLetters.charAt(calibrationIndex);p.setText("🔧 CALIBRAZIONE TASTIERA\n\nTocca la lettera "+n+"\n"+calibrationIndex+"/26");}else{manualCalibrationCenters=c.clone();saveManualCalibration(c,sw,sh);calibrationInProgress=false;removeCalibrationOverlay();calibratedCenters=c.clone();updateOverlayText("✅ CALIBRAZIONE COMPLETATA\n26/26 tasti salvati");}return true;});calibrationView=f;WindowManager.LayoutParams q=new WindowManager.LayoutParams(sw,sh,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);q.gravity=Gravity.TOP|Gravity.START;try{windowManager.addView(calibrationView,q);}catch(Exception e){calibrationView=null;calibrationInProgress=false;updateOverlayText("❌ Errore calibrazione: "+e.getClass().getSimpleName());}}
 private void removeCalibrationOverlay(){if(calibrationView!=null&&windowManager!=null)try{windowManager.removeView(calibrationView);}catch(Exception ignored){}calibrationView=null;}
 private void saveManualCalibration(float[] c,int w,int h){StringBuilder s=new StringBuilder();for(int i=0;i<c.length;i++){if(i>0)s.append(',');s.append(c[i]);}getSharedPreferences("codybot_keyboard",MODE_PRIVATE).edit().putString("centers",s.toString()).putInt("width",w).putInt("height",h).apply();}
 private void loadManualCalibration(){String raw=getSharedPreferences("codybot_keyboard",MODE_PRIVATE).getString("centers",null);if(raw==null)return;String[] p=raw.split(",");if(p.length!=52)return;try{float[] c=new float[52];for(int i=0;i<52;i++)c[i]=Float.parseFloat(p[i]);manualCalibrationCenters=c;calibratedCenters=c.clone();}catch(Exception ignored){manualCalibrationCenters=null;}}
 private void runKeyboardTest(){stopCompilation();String clean="ABCDEFGHIJKLMNOPQRSTUVWXYZ";compiling=true;calibratedCenters=manualCalibrationCenters!=null?manualCalibrationCenters.clone():null;updateOverlayText("🧪 TEST TASTIERA\nA-Z in corso...");DisplayMetrics dm=getResources().getDisplayMetrics();for(int i=0;i<clean.length();i++){final char c=clean.charAt(i);final float[] xy=calibratedKeyCenter(c,dm.widthPixels,dm.heightPixels);final int n=i+1;Runnable r=()->{if(compiling&&ScreenCaptureService.isServiceRunning()&&xy!=null){tap(xy[0],xy[1]);updateOverlayText("🧪 TEST TASTIERA\nPremuto: "+c+" ("+n+"/26)");}};pendingCompilation.add(r);handler.postDelayed(r,i*300L);}Runnable f=()->{if(compiling){compiling=false;pendingCompilation.clear();updateOverlayText("🧪 TEST TERMINATO\nControlla quali lettere sono state digitate.");}};pendingCompilation.add(f);handler.postDelayed(f,clean.length()*300L+500L);}
 private void fillAnswer(String answer){stopCompilation();final String clean=answer.toUpperCase().replaceAll("[^A-Z]","");if(clean.isEmpty())return;compiling=true;calibratedCenters=manualCalibrationCenters!=null?manualCalibrationCenters.clone():null;updateOverlayText("🟢 COMPILAZIONE\nRISPOSTA: "+clean+"\nControllo lettere già presenti...");if(Build.VERSION.SDK_INT>=30){takeScreenshot(android.view.Display.DEFAULT_DISPLAY,getMainExecutor(),new TakeScreenshotCallback(){public void onSuccess(ScreenshotResult r){Bitmap b=null;try{HardwareBuffer hb=r.getHardwareBuffer();ColorSpace cs=r.getColorSpace();if(hb!=null)b=Bitmap.wrapHardwareBuffer(hb,cs);findExistingLettersAndSchedule(b,clean);}catch(Exception e){scheduleAnswerTaps(clean,new java.util.HashSet<>());}finally{try{r.getHardwareBuffer().close();}catch(Exception ignored){}}}public void onFailure(int code){scheduleAnswerTaps(clean,new java.util.HashSet<>());}});}else scheduleAnswerTaps(clean,new java.util.HashSet<>());}
 private void findExistingLettersAndSchedule(Bitmap b,String clean){if(b==null||recognizer==null){scheduleAnswerTaps(clean,new java.util.HashSet<>());return;}final Bitmap source=b.copy(Bitmap.Config.ARGB_8888,false);if(source==null){scheduleAnswerTaps(clean,new java.util.HashSet<>());return;}final int h=source.getHeight();final int top=(int)(h*.35f);final int bottom=(int)(h*.78f);final Bitmap crop=Bitmap.createBitmap(source,0,top,source.getWidth(),Math.max(1,bottom-top));source.recycle();final Bitmap scaled=Bitmap.createScaledBitmap(crop,source.getWidth()>0?source.getWidth()*2:1,Math.max(1,crop.getHeight()*2),true);crop.recycle();InputImage image=InputImage.fromBitmap(scaled,0);recognizer.process(image).addOnSuccessListener(result->{java.util.List<float[]> candidates=new java.util.ArrayList<>();for(Text.TextBlock block:result.getTextBlocks())for(Text.Line line:block.getLines()){for(Text.Element el:line.getElements()){String s=el.getText()==null?"":el.getText().trim().toUpperCase();android.graphics.Rect r=el.getBoundingBox();if(r!=null&&s.matches("[A-Z]"))candidates.add(new float[]{r.centerX(),r.centerY(),s.charAt(0)});}}java.util.List<Character> detected=new java.util.ArrayList<>();if(!candidates.isEmpty()){for(int pass=0;pass<2&&detected.size()<clean.length();pass++){float bestY=0;int bestCount=0;for(float[] a:candidates){int count=0;for(float[] q:candidates)if(Math.abs(q[1]-a[1])<(pass==0?90f:140f))count++;if(count>bestCount){bestCount=count;bestY=a[1];}}for(float[] a:candidates)if(Math.abs(a[1]-bestY)<(pass==0?90f:140f))detected.add((char)a[2]);if(detected.size()>clean.length())while(detected.size()>clean.length())detected.remove(detected.size()-1);}}java.util.Collections.sort(candidates,(a,q)->Float.compare(a[0],q[0]));if(!detected.isEmpty()){detected.clear();float bestY=0;int bestCount=0;for(float[] a:candidates){int count=0;for(float[] q:candidates)if(Math.abs(q[1]-a[1])<120f)count++;if(count>bestCount){bestCount=count;bestY=a[1];}}for(float[] a:candidates)if(Math.abs(a[1]-bestY)<120f)detected.add((char)a[2]);}java.util.Set<Integer> existing=alignDetectedLetters(clean,detected);scheduleAnswerTaps(clean,existing);try{scaled.recycle();}catch(Exception ignored){}}).addOnFailureListener(e->{try{scaled.recycle();}catch(Exception ignored){}scheduleAnswerTaps(clean,new java.util.HashSet<>());});}
 private void hideOverlay(){stopCompilation();handler.removeCallbacks(overlayChecker);removeCalibrationOverlay();if(overlayView!=null&&windowManager!=null)try{windowManager.removeView(overlayView);}catch(Exception ignored){}overlayView=null;statusText=null;}
 private java.util.Set<Integer> alignDetectedLetters(String clean,java.util.List<Character> detected){java.util.Set<Integer> matched=new java.util.HashSet<>();if(detected==null||detected.isEmpty())return matched;int n=clean.length(),m=detected.size();int[][] dp=new int[n+1][m+1];for(int i=1;i<=n;i++)for(int j=1;j<=m;j++){int best=Math.max(dp[i-1][j],dp[i][j-1]);if(clean.charAt(i-1)==detected.get(j-1))best=Math.max(best,dp[i-1][j-1]+1);dp[i][j]=best;}int i=n,j=m;while(i>0&&j>0){if(clean.charAt(i-1)==detected.get(j-1)&&dp[i][j]==dp[i-1][j-1]+1){matched.add(i-1);i--;j--;}else if(dp[i-1][j]>=dp[i][j-1])i--;else j--;}return matched;}
 private void scheduleAnswerTaps(String clean,java.util.Set<Integer> existing){if(!compiling)return;DisplayMetrics dm=getResources().getDisplayMetrics();float w=dm.widthPixels,h=dm.heightPixels;int index=0,skipped=0;for(int i=0;i<clean.length();i++){if(existing.contains(i)){skipped++;continue;}final char c=clean.charAt(i);final float[] xy=calibratedKeyCenter(c,w,h);if(xy==null)continue;final long d=index*240L;index++;Runnable r=()->{if(compiling&&ScreenCaptureService.isServiceRunning())tap(xy[0],xy[1]);};pendingCompilation.add(r);handler.postDelayed(r,d);}final int n=clean.length(),s=skipped;Runnable f=()->{if(!compiling)return;compiling=false;pendingCompilation.clear();updateOverlayText("✅ COMPILATA: "+clean+"\nGià presenti: "+s+"/"+n);calibratedCenters=null;};pendingCompilation.add(f);handler.postDelayed(f,Math.max(300,index*240L+300L));}
 private float[] calibratedKeyCenter(char c,float w,float h){String a="QWERTYUIOP",b="ASDFGHJKL",d="ZXCVBNM";int i;if(manualCalibrationCenters!=null&&manualCalibrationCenters.length==52){int p=calibrationLetters.indexOf(c);if(p>=0)return new float[]{manualCalibrationCenters[p*2],manualCalibrationCenters[p*2+1]};}if(calibratedCenters!=null&&calibratedCenters.length>=38){if((i=a.indexOf(c))>=0)return new float[]{calibratedCenters[i*2],calibratedCenters[i*2+1]};if((i=b.indexOf(c))>=0){int p=10+i;return new float[]{calibratedCenters[p*2],calibratedCenters[p*2+1]};}if((i=d.indexOf(c))>=0){int p=19+i;return new float[]{calibratedCenters[p*2],calibratedCenters[p*2+1]};}}return keyCenter(c,w,h);}
 private float[] keyCenter(char c,float w,float h){String a="QWERTYUIOP",b="ASDFGHJKL",d="ZXCVBNM";int i;if((i=a.indexOf(c))>=0)return new float[]{w*(.05f+i*.10f),h*.77f};if((i=b.indexOf(c))>=0)return new float[]{w*(.10f+i*.10f),h*.855f};if((i=d.indexOf(c))>=0)return new float[]{w*(.25f+i*.10f),h*.94f};return null;}
 private void tap(float x,float y){Path p=new Path();p.moveTo(x,y);GestureDescription.StrokeDescription s=new GestureDescription.StrokeDescription(p,0,60);dispatchGesture(new GestureDescription.Builder().addStroke(s).build(),null,null);}
 private void stopCompilation(){for(Runnable r:pendingCompilation)handler.removeCallbacks(r);pendingCompilation.clear();compiling=false;if(statusText!=null)statusText.setText("🔴 STOP");}
 private void updateOverlayText(String m){Intent i=new Intent("com.codybot.UPDATE_OVERLAY");i.setPackage(getPackageName());i.putExtra("message",m);sendBroadcast(i);}
 @Override public void onInterrupt(){}
 @Override public void onDestroy(){stopCompilation();handler.removeCallbacks(overlayChecker);if(recognizer!=null)recognizer.close();try{unregisterReceiver(overlayReceiver);}catch(Exception ignored){}if(overlayView!=null&&windowManager!=null)try{windowManager.removeView(overlayView);}catch(Exception ignored){}overlayView=null;super.onDestroy();}
}
